version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting pipeline . . .
      - wget https://github.com/zricethezav/gitleaks/releases/download/v8.13.0/gitleaks_8.13.0_linux_x64.tar.gz
      - tar -xzf gitleaks_8.13.0_linux_x64.tar.gz
      - sudo install gitleaks /usr/bin
  build:
    commands:
      - echo Build started on `date`
      - echo Scanning with gitleaks $CODE_BRANCH...
      - git clone -b ${CODE_BRANCH} https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}.git
      - cd ${GITHUB_REPOSITORY}
      - gitleaks detect --report-path --report-format json gitleaks-report.json
      - gitleaks detect --baseline-path gitleaks.json  --report-format json --report-path findings.json 

  post_build:
    commands:
      - echo Build completed on `date`
      - cat gitleaks.json
      - cat findings.json 
artifacts:
  files: ${GITHUB_REPOSITORY}/findings.json 