version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting pipeline . . .
      - wget https://github.com/zricethezav/gitleaks/releases/download/v8.13.0/gitleaks_8.13.0_linux_x64.tar.gz
      - tar -xzf gitleaks_8.13.0_linux_x64.tar.gz
      - sudo install gitleaks /usr/bin
  build:
    commands:
      - echo Build started on `date`
      - echo Scanning with gitleaks $CODE_BRANCH...
      - rm -rf gitleaks-report.json
      - gitleaks detect --no-git --verbose --report-format json --report-path gitleaks-report.json --exit-code 0
      - echo "Build started on $(date)"
      - git clone https://github.com/awslabs/git-secrets
      - cd git-secrets
      - make install
      - cd $CODEBUILD_SRC_DIR
      - ls -lrta
      - cd git-secrets
      - git secrets --install
      - git secrets --register-aws
      ## Adding additional patterns, for example password
      #- git secrets --add password\s*=\s*.+
      - git secrets --scan -r .

  post_build:
    commands:
      - echo Build completed on `date`
      - ls -lrt
      - cat gitleaks-report.json
artifacts:
  files: gitleaks-report.json
  type: zip
  files: '**/*'