version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - "apt update"
      - "apt install rpm -y"
      - "pip3 install boto3"
      - "wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb"
      - "dpkg -i trivy_0.27.1_Linux-64bit.deb"
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - "docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_NAME:latest ."
  build:
    commands:
      - trivy image -f json -o results.json --exit-code 0 --severity HIGH,CRITICAL $ECR_REGISTRY/$ECR_REPOSITORY_NAME:latest
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAME:latest
  post_build:
    commands:
      - echo trivy scan completed on `date`
      - cat results.json
artifacts:
  files: results.json