version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - "apt update"
      - "apt install rpm -y"
      - "pip3 install boto3"
      - "wget https://github.com/aquasecurity/trivy/releases/download/v0.1.6/trivy_0.1.6_Linux-64bit.deb"
      - "dpkg -i trivy_0.1.6_Linux-64bit.deb"
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - echo $(date +%Y-%m-%d-%H-%M) > /tmp/timestamp
      - echo $(cat /tmp/timestamp)
      - TAG="DEVEL-$(cat /tmp/timestamp)"
      - echo Building the Docker image...
      - echo $IMAGE_REPO_NAME:$TAG
      - docker build -t $IMAGE_REPO_NAME:$TAG .
  build:
    commands:
      - trivy -f json -o results.json --exit-code 0 --severity HIGH,MEDIUM,LOW --quiet --auto-refresh $IMAGE_REPO_NAME:$TAG
      - trivy -f json -o results.json --exit-code 1 --severity HIGH,CRITICAL --quiet --auto-refresh $IMAGE_REPO_NAME:$TAG
      - docker tag $IMAGE_REPO_NAME:$TAG $ECR_REGISTRY/$IMAGE_REPO_NAME:latest
      - docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo trivy scan completed on `date`
      - python3 sechub_parser.py
      - echo Report Sent to Security Hub on `date`