version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting pipeline . . .
      - wget https://github.com/zricethezav/gitleaks/releases/download/v8.13.0/gitleaks_8.13.0_linux_x64.tar.gz
      - tar -xzf gitleaks_8.13.0_linux_x64.tar.gz
      - sudo install gitleaks /usr/bin
  build:
    commands:
      - echo Build started on `date`
      - echo Scanning with gitleaks $CODE_BRANCH...
      - git clone -b ${CODE_BRANCH} https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}.git
      - cd ${GITHUB_REPOSITORY}
      - gitleaks detect --no-git --report-path --report-format json gitleaks-report.json
      - ls -lrt

  post_build:
    commands:
      - echo Build completed on `date`
      - cd ${GITHUB_REPOSITORY}
      - cat gitleaks-report.json
artifacts:
  files: ${GITHUB_REPOSITORY}/gitleaks-report.json